FROM node:23.5.0-alpine3.20 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . ./
RUN npm run build

FROM caddy:2.8.4-alpine
COPY --from=builder /app/dist /srv
COPY ./Caddyfile.prod /etc/caddy/Caddyfile
