services:
  engine:
    build: ./chess-engine/service
    ports:
      - "5000:5000"
    environment:
      PORT: 5000

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

  backend:
    image: node:23.5.0-alpine3.20
    user: "${HOST_UID}:${HOST_GID}"
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BEST_MOVE_URL: http://engine:5000/best-move
      AUTH_PROVIDER_JWKS_URI: http://keycloak:8080/realms/my-realm/protocol/openid-connect/certs
    command: |
      sh -c "if [ ! -d node_modules ]; then
        npm install;
      fi &&
      npm run start:dev"

  frontend:
    image: node:23.5.0-alpine3.20
    user: "${HOST_UID}:${HOST_GID}"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      FORCE_COLOR: true
      VITE_FROM_DOCKER: true
    command: |
      sh -c "if [ ! -d node_modules ]; then
        npm install;
      fi &&
      npm run dev"

volumes:
  keycloak_data:
