services:
  engine:
    build: ./chess-engine/service
    image: ${CONTAINER_REGISTRY_HOST:?error}/${ENGINE_IMAGE:?error}
    restart: unless-stopped
    environment:
      PORT: 5000

  database:
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:?error}
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: ${CONTAINER_REGISTRY_HOST:?error}/${BACKEND_IMAGE:?error}
    restart: unless-stopped
    environment:
      PORT: 8000
      BEST_MOVE_URL: http://engine:5000/best-move
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID:?error}
      AUTH_PROVIDER_ROOT_URL: ${AUTH_PROVIDER_ROOT_URL:?error}
      AUTH_PROVIDER_JWKS_URI: ${AUTH_PROVIDER_JWKS_URI:?error}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:?error}
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        AUTH_PROVIDER_ROOT_URL: ${AUTH_PROVIDER_ROOT_URL:?error}
        AUTH_CLIENT_ID: ${AUTH_CLIENT_ID:?error}
        AUTH_CLIENT_URL_ORIGIN: ${AUTH_CLIENT_URL_ORIGIN:?error}
        AUTH_CLIENT_REDIRECT_PATH: ${AUTH_CLIENT_REDIRECT_PATH:?error}
        AUTH_CLIENT_POST_LOGOUT_REDIRECT_PATH: ${AUTH_CLIENT_POST_LOGOUT_REDIRECT_PATH:?error}
    image: ${CONTAINER_REGISTRY_HOST:?error}/${FRONTEND_IMAGE:?error}
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAIN: ${DOMAIN:?error}
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pg_data:
  caddy_data:
  caddy_config:
