services:
  engine:
    build: ./stockfish/service
    ports:
      - "5000:5000"
    environment:
      PORT: 5000

  backend:
    image: node:23.5.0-alpine3.20
    user: "${HOST_UID}:${HOST_GID}"
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BEST_MOVE_URL: http://engine:5000/best-move
    command: |
      sh -c "if [ ! -d node_modules ]; then
        npm install;
      fi &&
      npm run start:dev"

  frontend:
    image: node:23.5.0-alpine3.20
    user: "${HOST_UID}:${HOST_GID}"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      FORCE_COLOR: true
      VITE_FROM_DOCKER: true
    command: |
      sh -c "if [ ! -d node_modules ]; then
        npm install;
      fi &&
      npm run dev"
