FROM node:23.5.0-alpine3.20 AS builder
WORKDIR /app
COPY --chown=node:node package.json package-lock.json ./
RUN npm ci
COPY --chown=node:node . ./
RUN npm run build
ENV NODE_ENV=production
RUN npm ci --omit=dev
USER node

FROM node:23.5.0-alpine3.20 AS server
WORKDIR /app
COPY --chown=node:node --from=builder /app/dist ./dist
COPY --chown=node:node --from=builder /app/node_modules ./node_modules
USER node

EXPOSE 8000
CMD ["node", "dist/main"]
