services:
  engine:
    build: ./service
    env_file: ./tests/config/.env.${SUITE}
    environment:
      - PORT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 2s
      timeout: 2s
      retries: 10

  tester:
    build: ./tests
    command: -- integration.${SUITE}.test.js
    environment:
      - API_URL=http://engine:5000/best-move
    depends_on:
      engine:
        condition: service_healthy
